package scripts;

public enum EnvironmentVariables {
    DETECT_LATEST_RELEASE_VERSION,
    DETECT_VERSION_KEY,
    DETECT_SOURCE,
    DETECT_JAR_PATH,
    DETECT_JAR_DOWNLOAD_DIR,
    DETECT_JAVA_OPTS,
    DETECT_CURL_OPTS,
    DETECT_DOWNLOAD_ONLY,
    DETECT_JAVA_PATH,
    JAVA_HOME
}
